# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3099d6bcbbd8cd656bee0477ed507c997f385f59a93d490ab6f6234d7de0708a99054a8ef6268f927f6934e6bb1b6821c78de53df7958fd427b4c2e2b567133f

test:
  secret_key_base: 1fb9c36adaba46462d4ad46b91cb7301ebf078d96afdafe6e26c4a8097d942067c6e0aa0838bab87a3f97b24a18f7c65f74f62a3f2001007e8b30dca6e7a8cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
